package dev.oscarnylander.tddsample

import androidx.test.rule.ActivityTestRule
import com.agoda.kakao.screen.Screen.Companion.onScreen
import com.apollographql.apollo.api.toJson
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.junit.Rule
import org.junit.Test

class ExampleActivityDataTest {
    @get:Rule
    val activityRule = ActivityTestRule(ExampleActivity::class.java, false, false)

    @Test
    fun shouldShowDataOnScreen() {
        MockWebServer().use { webServer ->
            webServer.start(8080)
            webServer.enqueue(MockResponse().setBody(DATA.toJson()))

            activityRule.launchActivity(null)

            onScreen<ExampleScreen> {
                film { hasText("The Empire Strikes Back") }
            }
        }
    }

    companion object {
        // Data class generated by `apollo-android`, based on your `.graphql`-files
        private val DATA = FilmQuery.Data(
            film = FilmQuery.Film(
                title = "The Empire Strikes Back"
            )
        )
    }
}