package dev.oscarnylander.tddsample

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.rule.ActivityTestRule
import com.agoda.kakao.screen.Screen.Companion.onScreen
import com.apollographql.apollo.ApolloClient
import com.apollographql.apollo.api.toJson
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.awaitility.Duration.ONE_SECOND
import org.awaitility.kotlin.atMost
import org.awaitility.kotlin.await
import org.awaitility.kotlin.untilAsserted
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.koin.test.KoinTest
import org.koin.test.inject

@RunWith(AndroidJUnit4::class)
class ExampleActivityAnimationTest : KoinTest {
    private val apolloClient: ApolloClient by inject()

    @get:Rule
    val activityRule = ActivityTestRule(ExampleActivity::class.java, false, false)

    @Before
    fun setup() {
        apolloClient.clearNormalizedCache()
    }

    @Test
    fun shouldDoSomethingWhenClicked() {
        MockWebServer().use { webServer ->
            webServer.start(8080)
            webServer.enqueue(MockResponse().setBody(DATA.toJson()))

            activityRule.launchActivity(null)

            onScreen<ExampleScreen> {
                button { click() }
                await atMost ONE_SECOND untilAsserted  {
                    viewShownAfterAnimation {
                        isVisible()
                    }
                }
            }
        }
    }

    companion object {
        // Data class generated by `apollo-android`, based on your `.graphql`-files
        private val DATA = FilmQuery.Data(
            film = FilmQuery.Film(
                title = "The Empire Strikes Back"
            )
        )
    }
}
